### ISSUE TITLE
molpal crush due to invalid smiles 

### ISSUE THREAD

**Issue by likun1212** [coleygroup/molpal#25]
Basically, rdkit mmff can't generate conformation for some smiles, which cause molpal crush.

########################################################################
File "/work/home/aixplorerbio_wz/ylk/molpal-main/run.py", line 71, in <module>
    main()
  File "/work/home/aixplorerbio_wz/ylk/molpal-main/run.py", line 55, in main
    explorer.run()
  File "/work/home/aixplorerbio_wz/ylk/molpal-main/molpal/explorer.py", line 317, in run
    self.explore_initial()
  File "/work/home/aixplorerbio_wz/ylk/molpal-main/molpal/explorer.py", line 355, in explore_initial
    new_scores = self.objective(inputs)
  File "/work/home/aixplorerbio_wz/ylk/molpal-main/molpal/objectives/base.py", line 27, in __call__
    return self.forward(*args, **kwargs)
  File "/work/home/aixplorerbio_wz/ylk/molpal-main/molpal/objectives/docking.py", line 90, in forward
    Y = self.c * self.virtual_screen(smis)
  File "/work/home/aixplorerbio_wz/miniconda3/envs/molpal/lib/python3.8/site-packages/pyscreener/docking/screen.py", line 166, in __call__
    completed_simulationsss = self.run(planned_simulationsss)
  File "/work/home/aixplorerbio_wz/miniconda3/envs/molpal/lib/python3.8/site-packages/pyscreener/docking/screen.py", line 275, in run
    return [
  File "/work/home/aixplorerbio_wz/miniconda3/envs/molpal/lib/python3.8/site-packages/pyscreener/docking/screen.py", line 276, in <listcomp>
    [ray.get(refs) for refs in refss]
  File "/work/home/aixplorerbio_wz/miniconda3/envs/molpal/lib/python3.8/site-packages/pyscreener/docking/screen.py", line 276, in <listcomp>
    [ray.get(refs) for refs in refss]
  File "/work/home/aixplorerbio_wz/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/work/home/aixplorerbio_wz/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/worker.py", line 1733, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::prepare_and_run() (pid=3206, ip=10.3.3.62)
  File "/work/home/aixplorerbio_wz/miniconda3/envs/molpal/lib/python3.8/site-packages/pyscreener/docking/vina/runner.py", line 67, in prepare_and_run
    VinaRunner.prepare_ligand(data)
  File "/work/home/aixplorerbio_wz/miniconda3/envs/molpal/lib/python3.8/site-packages/pyscreener/docking/vina/runner.py", line 75, in prepare_ligand
    VinaRunner.prepare_from_smi(data)
  File "/work/home/aixplorerbio_wz/miniconda3/envs/molpal/lib/python3.8/site-packages/pyscreener/docking/vina/runner.py", line 97, in prepare_from_smi
    Chem.MMFFOptimizeMolecule(mol)
ValueError: Bad Conformer Id
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/work/home/aixplorerbio_wz/ylk/molpal-main/molpal/objectives/docking.py", line 101, in cleanup
    writer.writerow(field.name for field in dataclasses.fields(results[0]))
IndexError: list index out of range
^MDocking:   1%|▏         | 585/40000 [23:56<26:53:23,  2.46s/ligand]
###################################################################################################

**Comment by davidegraff** [comment]
This is an error in the pyscreener library. It was addressed in an update a few months ago. I suggest updating to the newest version and see if this error persists
